const MAJORS = {
  environmental: 'Environmental',
  social: 'Social',
  governance: 'Governance'
}

const SUBCATEGORIES = {
  environmental: [
    'climate_emissions',
    'energy',
    'water',
    'waste_circularity',
    'biodiversity_land_use',
    'pollution',
    'supply_chain_environment'
  ],
  social: [
    'labor_employment',
    'health_safety_wellbeing',
    'dei',
    'human_rights',
    'community_social_impact',
    'product_customer_welfare',
    'talent_development'
  ],
  governance: [
    'board_oversight',
    'ethics_anti_corruption',
    'risk_compliance',
    'data_privacy_cybersecurity',
    'executive_remuneration',
    'transparency_reporting',
    'supply_chain_governance'
  ]
}

const SUBCATEGORY_LABELS = {
  climate_emissions: 'Climate & Emissions',
  energy: 'Energy',
  water: 'Water',
  waste_circularity: 'Waste & Circularity',
  biodiversity_land_use: 'Biodiversity & Land Use',
  pollution: 'Pollution',
  supply_chain_environment: 'Supply Chain (Environment)',

  labor_employment: 'Labor & Employment',
  health_safety_wellbeing: 'Health, Safety & Wellbeing',
  dei: 'Diversity, Equity & Inclusion (DEI)',
  human_rights: 'Human Rights',
  community_social_impact: 'Community & Social Impact',
  product_customer_welfare: 'Product Responsibility & Customer Welfare',
  talent_development: 'Talent Development',

  board_oversight: 'Board & Oversight',
  ethics_anti_corruption: 'Ethics & Anti-Corruption',
  risk_compliance: 'Risk Management & Compliance',
  data_privacy_cybersecurity: 'Data Privacy & Cybersecurity',
  executive_remuneration: 'Executive Remuneration & Incentives',
  transparency_reporting: 'Transparency & Reporting',
  supply_chain_governance: 'Supply Chain Management (Governance)'
}

const SUBCATEGORY_TO_MAJOR = (() => {
  const m = {}
  for (const major of Object.keys(SUBCATEGORIES)) {
    for (const sub of SUBCATEGORIES[major]) {
      m[sub] = major
    }
  }
  return m
})()

const WORDS = {
  climate_emissions: [
    'climate',
    'global warming',
    'temperature target',
    'co2',
    'ghg',
    'greenhouse gas',
    'greenhouse gases',
    'emission',
    'emissions',
    'scope 1',
    'scope 2',
    'scope 3',
    'carbon',
    'decarbon',
    'decarbonization',
    'net zero',
    'carbon footprint',

    'κλίμα',
    'κλιμα',
    'κλιματική αλλαγή',
    'κλιματικη αλλαγη',
    'υπερθέρμανση',
    'υπερθερμανση',
    'διοξείδιο του άνθρακα',
    'διοξειδιο του ανθρακα',
    'αέρια θερμοκηπίου',
    'αερια θερμοκηπιου',
    'εκπομπή',
    'εκπομπη',
    'εκπομπές',
    'εκπομπες',
    'άνθρακας',
    'ανθρακας',
    'ανθρακικό αποτύπωμα',
    'ανθρακικο αποτυπωμα',
    'μηδενικές εκπομπές',
    'μηδενικες εκπομπες',

    'clima',
    'cambio climático',
    'cambio climatico',
    'calentamiento global',
    'gases de efecto invernadero',
    'emisión',
    'emision',
    'emisiones',
    'carbono',
    'huella de carbono',
    'cero neto',

    'klima',
    'klimawandel',
    'globale erwärmung',
    'globale erwarmung',
    'treibhausgas',
    'treibhausgase',
    'emission',
    'emissionen',
    'kohlenstoff',
    'co2-fußabdruck',
    'co2-fussabdruck',
    'netto null',

    'klima',
    'klimaendring',
    'klimaendringer',
    'global oppvarming',
    'klimagass',
    'klimagasser',
    'utslipp',
    'karbon',
    'karbonavtrykk',
    'netto null'
  ],

  energy: [
    'energy',
    'electricity',
    'fuel',
    'diesel',
    'gasoline',
    'petrol',
    'consumption',
    'efficiency',
    'energy saving',
    'renewable',
    'renewables',
    'solar',
    'wind',
    'heat',
    'heating',
    'lighting',

    'ενέργεια',
    'ενεργεια',
    'ηλεκτρικό',
    'ηλεκτρικο',
    'ηλεκτρική ενέργεια',
    'ηλεκτρικη ενεργεια',
    'ρεύμα',
    'ρευμα',
    'καύσιμο',
    'καυσιμο',
    'καύσιμα',
    'καυσιμα',
    'ντίζελ',
    'ντιζελ',
    'βενζίνη',
    'βενζινη',
    'κατανάλωση',
    'καταναλωση',
    'αποδοτικότητα',
    'αποδοτικοτητα',
    'εξοικονόμηση ενέργειας',
    'εξοικονομηση ενεργειας',
    'ανανεώσιμη',
    'ανανεωσιμη',
    'ηλιακή',
    'ηλιακη',
    'αιολική',
    'αιολικη',
    'φωτισμός',
    'φωτισμος',

    'energía',
    'energia',
    'electricidad',
    'combustible',
    'diésel',
    'diesel',
    'gasolina',
    'consumo',
    'eficiencia',
    'ahorro energético',
    'ahorro energetico',
    'renovable',
    'renovables',
    'solar',
    'eólica',
    'eolica',
    'calefacción',
    'calefaccion',
    'iluminación',
    'iluminacion',

    'energie',
    'strom',
    'elektrizität',
    'elektrizitat',
    'kraftstoff',
    'diesel',
    'benzin',
    'verbrauch',
    'effizienz',
    'energieeinsparung',
    'erneuerbar',
    'erneuerbare',
    'solar',
    'wind',
    'heizung',
    'beleuchtung',

    'energi',
    'elektrisitet',
    'strøm',
    'strom',
    'drivstoff',
    'diesel',
    'bensin',
    'forbruk',
    'effektivitet',
    'energisparing',
    'fornybar',
    'fornybare',
    'sol',
    'vind',
    'oppvarming',
    'belysning'
  ],

  water: [
    'water',
    'water use',
    'water management',
    'wastewater',
    'sewage',
    'discharge',
    'stormwater',
    'leak',
    'leakage',

    'νερό',
    'νερο',
    'ύδρευση',
    'υδρευση',
    'χρήση νερού',
    'χρηση νερου',
    'διαχείριση νερού',
    'διαχειριση νερου',
    'λύματα',
    'λυματα',
    'απόβλητα νερά',
    'αποβλητα νερα',
    'αποχέτευση',
    'αποχετευση',
    'όμβρια',
    'ομβρια',
    'διαρροή νερού',
    'διαρροη νερου',

    'agua',
    'uso de agua',
    'gestión del agua',
    'gestion del agua',
    'aguas residuales',
    'alcantarillado',
    'descarga',
    'fuga de agua',
    'fuga',

    'wasser',
    'wassernutzung',
    'wassermanagement',
    'abwasser',
    'kanalisation',
    'einleitung',
    'regenwasser',
    'leck',
    'leckage',

    'vann',
    'vannbruk',
    'vannforvaltning',
    'avløpsvann',
    'avlopsvann',
    'kloakk',
    'utslipp til vann',
    'overvann',
    'lekkasje'
  ],

  waste_circularity: [
    'waste',
    'recycle',
    'recycling',
    'recyclable',
    'landfill',
    'circular',
    'circularity',
    'segregation',
    'sorting',
    'reuse',
    'compost',

    'απόβλητα',
    'αποβλητα',
    'σκουπίδια',
    'σκουπιδια',
    'ανακύκλωση',
    'ανακυκλωση',
    'ανακυκλώσιμο',
    'ανακυκλωσιμο',
    'χωματερή',
    'χωματερη',
    'κυκλικότητα',
    'κυκλικοτητα',
    'διαλογή',
    'διαλογη',
    'επαναχρησιμοποίηση',
    'επαναχρησιμοποιηση',
    'κομπόστ',
    'κομποστ',

    'residuos',
    'basura',
    'reciclaje',
    'reciclar',
    'reciclable',
    'vertedero',
    'circular',
    'circularidad',
    'separación',
    'separacion',
    'clasificación',
    'clasificacion',
    'reutilización',
    'reutilizacion',
    'compost',

    'abfall',
    'müll',
    'mull',
    'recycling',
    'recyceln',
    'recycelbar',
    'deponie',
    'kreislauf',
    'kreislaufwirtschaft',
    'trennung',
    'sortierung',
    'wiederverwendung',
    'kompost',

    'avfall',
    'søppel',
    'soppel',
    'resirkulering',
    'resirkulere',
    'resirkulerbar',
    'deponi',
    'sirkulær',
    'sirkulaer',
    'sirkularitet',
    'sortering',
    'gjenbruk',
    'kompost'
  ],

  biodiversity_land_use: [
    'biodiversity',
    'habitat',
    'ecosystem',
    'species',
    'flora',
    'fauna',
    'land use',
    'deforestation',
    'reforestation',
    'wetland',
    'marine',
    'coastal',

    'βιοποικιλότητα',
    'βιοποικιλοτητα',
    'οικότοπος',
    'οικοτοπος',
    'οικοσύστημα',
    'οικοσυστημα',
    'είδη',
    'ειδη',
    'χλωρίδα',
    'χλωριδα',
    'πανίδα',
    'πανιδα',
    'χρήση γης',
    'χρηση γης',
    'αποψίλωση',
    'αποψιλωση',
    'αναδάσωση',
    'αναδασωση',
    'υγρότοπος',
    'υγροτοπος',
    'θαλάσσιος',
    'θαλασσιος',
    'παράκτιος',
    'παρακτιος',

    'biodiversidad',
    'hábitat',
    'habitat',
    'ecosistema',
    'especies',
    'flora',
    'fauna',
    'uso del suelo',
    'deforestación',
    'deforestacion',
    'reforestación',
    'reforestacion',
    'humedal',
    'marino',
    'costero',

    'biodiversität',
    'biodiversitat',
    'lebensraum',
    'ökosystem',
    'okosystem',
    'arten',
    'flora',
    'fauna',
    'landnutzung',
    'entwaldung',
    'aufforstung',
    'feuchtgebiet',
    'marin',
    'küste',
    'kuste',

    'biologisk mangfold',
    'naturmangfold',
    'habitat',
    'økosystem',
    'okosystem',
    'arter',
    'flora',
    'fauna',
    'arealbruk',
    'avskoging',
    'skogplanting',
    'våtmark',
    'vatmark',
    'marin',
    'kyst'
  ],

  pollution: [
    'pollution',
    'spill',
    'oil spill',
    'air quality',
    'noise',
    'odour',
    'odor',
    'contamination',
    'leak',
    'chemicals',

    'ρύπανση',
    'ρυπανση',
    'μόλυνση',
    'μολυνση',
    'διαρροή',
    'διαρροη',
    'πετρελαιοκηλίδα',
    'πετρελαιοκηλιδα',
    'διαρροή πετρελαίου',
    'διαρροη πετρελαιου',
    'ποιότητα αέρα',
    'ποιοτητα αερα',
    'θόρυβος',
    'θορυβος',
    'οσμή',
    'οσμη',
    'χημικά',
    'χημικα',

    'contaminación',
    'contaminacion',
    'derrame',
    'derrame de petróleo',
    'derrame de petroleo',
    'calidad del aire',
    'ruido',
    'olor',
    'químicos',
    'quimicos',

    'verschmutzung',
    'verunreinigung',
    'ölverschmutzung',
    'olverschmutzung',
    'ölunfall',
    'olunfall',
    'luftqualität',
    'luftqualitat',
    'lärm',
    'larm',
    'geruch',
    'chemikalien',

    'forurensning',
    'utslipp',
    'oljeutslipp',
    'luftkvalitet',
    'støy',
    'stoy',
    'lukt',
    'kjemikalier'
  ],

  supply_chain_environment: [
    'supplier',
    'procurement',
    'sourcing',
    'vendor',
    'logistics',
    'transport',
    'fleet',
    'upstream',
    'downstream',
    'environmental requirement',
    'environmental criteria',

    'προμηθευτής',
    'προμηθευτης',
    'προμηθευτές',
    'προμηθευτες',
    'προμήθειες',
    'προμηθειες',
    'αγορές',
    'αγορες',
    'εφοδιαστική',
    'εφοδιαστικη',
    'μεταφορές',
    'μεταφορες',
    'στόλος',
    'στολος',
    'περιβαλλοντικά κριτήρια',
    'περιβαλλοντικα κριτηρια',

    'proveedor',
    'proveedores',
    'compras',
    'abastecimiento',
    'logística',
    'logistica',
    'transporte',
    'flota',
    'criterios ambientales',
    'requisitos ambientales',

    'lieferant',
    'lieferanten',
    'beschaffung',
    'einkauf',
    'logistik',
    'transport',
    'flotte',
    'umweltanforderung',
    'umweltkriterien',

    'leverandør',
    'leverandor',
    'leverandører',
    'leverandorer',
    'anskaffelse',
    'innkjøp',
    'innkjop',
    'logistikk',
    'transport',
    'flåte',
    'flate',
    'miljøkrav',
    'miljokrav',
    'miljøkriterier',
    'miljokriterier'
  ],

  labor_employment: [
    'labor',
    'labour',
    'employment',
    'employee',
    'worker',
    'wage',
    'salary',
    'overtime',
    'work hours',
    'shift',
    'contract',
    'union',
    'collective agreement',
    'hiring',
    'firing',

    'εργασία',
    'εργασια',
    'απασχόληση',
    'απασχοληση',
    'εργαζόμενος',
    'εργαζομενος',
    'εργάτης',
    'εργατης',
    'μισθός',
    'μισθος',
    'υπερωρία',
    'υπερωρια',
    'ωράριο',
    'ωραριο',
    'βάρδια',
    'βαρδια',
    'σύμβαση',
    'συμβαση',
    'σωματείο',
    'σωματειο',
    'πρόσληψη',
    'προσληψη',
    'απόλυση',
    'απολυση',

    'trabajo',
    'empleo',
    'empleado',
    'trabajador',
    'salario',
    'sueldo',
    'horas extra',
    'jornada laboral',
    'turno',
    'contrato',
    'sindicato',
    'convenio colectivo',
    'contratación',
    'contratacion',
    'despido',

    'arbeit',
    'beschäftigung',
    'beschaftigung',
    'mitarbeiter',
    'arbeitnehmer',
    'lohn',
    'gehalt',
    'überstunden',
    'uberstunden',
    'arbeitszeit',
    'schicht',
    'vertrag',
    'gewerkschaft',
    'tarifvertrag',
    'einstellung',
    'kündigung',
    'kundigung',

    'arbeid',
    'sysselsetting',
    'ansatt',
    'arbeider',
    'lønn',
    'lonn',
    'overtid',
    'arbeidstid',
    'skift',
    'kontrakt',
    'fagforening',
    'tariffavtale',
    'ansettelse',
    'oppsigelse'
  ],

  health_safety_wellbeing: [
    'safety',
    'health',
    'ohs',
    'occupational',
    'incident',
    'accident',
    'hazard',
    'near miss',
    'ppe',
    'wellbeing',
    'fatigue',
    'stress',
    'injury',

    'ασφάλεια',
    'ασφαλεια',
    'υγεία',
    'υγεια',
    'εργασιακή ασφάλεια',
    'εργασιακη ασφαλεια',
    'εργατικό ατύχημα',
    'εργατικο ατυχημα',
    'ατύχημα',
    'ατυχημα',
    'περιστατικό',
    'περιστατικο',
    'κίνδυνος',
    'κινδυνος',
    'παρ’ ολίγον',
    'παρ ολιγον',
    'μέσα ατομικής προστασίας',
    'μεσα ατομικης προστασιας',
    'ευημερία',
    'ευημερια',
    'κόπωση',
    'κοπωση',
    'στρες',
    'τραυματισμός',
    'τραυματισμος',

    'seguridad',
    'salud',
    'salud laboral',
    'incidente',
    'accidente',
    'peligro',
    'riesgo',
    'casi accidente',
    'epi',
    'bienestar',
    'fatiga',
    'estrés',
    'estres',
    'lesión',
    'lesion',

    'sicherheit',
    'gesundheit',
    'arbeitsschutz',
    'vorfall',
    'unfall',
    'gefahr',
    'beinaheunfall',
    'psa',
    'wohlbefinden',
    'ermüdung',
    'ermudung',
    'stress',
    'verletzung',

    'sikkerhet',
    'helse',
    'arbeidsmiljø',
    'arbeidsmiljo',
    'hendelse',
    'ulykke',
    'fare',
    'nestenulykke',
    'verneutstyr',
    'velvære',
    'velvaere',
    'utmattelse',
    'stress',
    'skade'
  ],

  dei: [
    'diversity',
    'inclusion',
    'inclusive',
    'equity',
    'equality',
    'gender',
    'dei',
    'non-discrimination',
    'harassment',
    'bullying',

    'διαφορετικότητα',
    'διαφορετικοτητα',
    'συμπερίληψη',
    'συμπεριληψη',
    'ισότητα',
    'ισοτητα',
    'ισοτιμία',
    'ισοτιμια',
    'φύλο',
    'φυλο',
    'διάκριση',
    'διακριση',
    'παρενόχληση',
    'παρενοχληση',
    'εκφοβισμός',
    'εκφοβισμος',

    'diversidad',
    'inclusión',
    'inclusion',
    'inclusivo',
    'equidad',
    'igualdad',
    'género',
    'genero',
    'discriminación',
    'discriminacion',
    'acoso',
    'intimidación',
    'intimidacion',

    'diversität',
    'diversitat',
    'inklusion',
    'gerechtigkeit',
    'gleichstellung',
    'gleichberechtigung',
    'geschlecht',
    'diskriminierung',
    'belästigung',
    'belastigung',
    'mobbing',

    'mangfold',
    'inkludering',
    'inkluderende',
    'likestilling',
    'likeverd',
    'kjønn',
    'kjonn',
    'diskriminering',
    'trakassering',
    'mobbing'
  ],

  human_rights: [
    'human rights',
    'forced labor',
    'forced labour',
    'child labor',
    'child labour',
    'modern slavery',
    'freedom of association',
    'right to',
    'abuse',
    'exploitation',

    'ανθρώπινα δικαιώματα',
    'ανθρωπινα δικαιωματα',
    'καταναγκαστική εργασία',
    'καταναγκαστικη εργασια',
    'παιδική εργασία',
    'παιδικη εργασια',
    'σύγχρονη δουλεία',
    'συγχρονη δουλεια',
    'ελευθερία του συνεταιρίζεσθαι',
    'ελευθερια του συνεταιριζεσθαι',
    'κακοποίηση',
    'κακοποιηση',
    'εκμετάλλευση',
    'εκμεταλλευση',

    'derechos humanos',
    'trabajo forzoso',
    'trabajo infantil',
    'esclavitud moderna',
    'libertad de asociación',
    'libertad de asociacion',
    'abuso',
    'explotación',
    'explotacion',

    'menschenrechte',
    'zwangsarbeit',
    'kinderarbeit',
    'moderne sklaverei',
    'vereinigungsfreiheit',
    'missbrauch',
    'ausbeutung',

    'menneskerettigheter',
    'tvangsarbeid',
    'barnearbeid',
    'moderne slaveri',
    'organisasjonsfrihet',
    'misbruk',
    'utnyttelse'
  ],

  community_social_impact: [
    'community',
    'local community',
    'social impact',
    'donation',
    'sponsorship',
    'volunteer',
    'outreach',
    'neighbour',
    'neighbor',
    'neighborhood',
    'stakeholder engagement',

    'κοινότητα',
    'κοινοτητα',
    'τοπική κοινότητα',
    'τοπικη κοινοτητα',
    'κοινωνικός αντίκτυπος',
    'κοινωνικος αντικτυπος',
    'δωρεά',
    'δωρεα',
    'χορηγία',
    'χορηγια',
    'εθελοντής',
    'εθελοντης',
    'γειτονιά',
    'γειτονια',
    'ενδιαφερόμενα μέρη',
    'ενδιαφερομενα μερη',

    'comunidad',
    'comunidad local',
    'impacto social',
    'donación',
    'donacion',
    'patrocinio',
    'voluntario',
    'vecino',
    'barrio',
    'partes interesadas',

    'gemeinschaft',
    'lokale gemeinschaft',
    'soziale wirkung',
    'spende',
    'sponsoring',
    'freiwillige',
    'nachbar',
    'nachbarschaft',
    'stakeholder',

    'samfunn',
    'lokalsamfunn',
    'sosial påvirkning',
    'sosial pavirkning',
    'donasjon',
    'sponsor',
    'frivillig',
    'nabo',
    'nabolag',
    'interessenter'
  ],

  product_customer_welfare: [
    'customer',
    'client',
    'product safety',
    'product quality',
    'complaint',
    'recall',
    'misleading',
    'marketing',
    'data on product use',
    'user safety',

    'πελάτης',
    'πελατης',
    'πελάτες',
    'πελατες',
    'ασφάλεια προϊόντος',
    'ασφαλεια προϊοντος',
    'ποιότητα προϊόντος',
    'ποιοτητα προϊοντος',
    'παράπονο',
    'παραπονο',
    'ανάκληση',
    'ανακληση',
    'παραπλανητικός',
    'παραπλανητικος',
    'μάρκετινγκ',
    'μαρκετινγκ',

    'cliente',
    'seguridad del producto',
    'calidad del producto',
    'queja',
    'reclamación',
    'reclamacion',
    'retirada',
    'engañoso',
    'enganoso',
    'marketing',
    'seguridad del usuario',

    'kunde',
    'produktsicherheit',
    'produktqualität',
    'produktqualitat',
    'beschwerde',
    'rückruf',
    'ruckruf',
    'irreführend',
    'irrefuhrend',
    'marketing',
    'nutzersicherheit',

    'kunde',
    'klient',
    'produktsikkerhet',
    'produktkvalitet',
    'klage',
    'tilbakekalling',
    'villedende',
    'markedsføring',
    'markedsforing',
    'brukersikkerhet'
  ],

  talent_development: [
    'training',
    'course',
    'module',
    'lesson',
    'upskill',
    'reskill',
    'capacity building',
    'talent',
    'development program',
    'career',
    'performance review',

    'εκπαίδευση',
    'εκπαιδευση',
    'κατάρτιση',
    'καταρτιση',
    'μάθημα',
    'μαθημα',
    'ενότητα',
    'ενοτητα',
    'δεξιότητες',
    'δεξιοτητες',
    'ανάπτυξη δεξιοτήτων',
    'αναπτυξη δεξιοτητων',
    'καριέρα',
    'καριερα',
    'αξιολόγηση απόδοσης',
    'αξιολογηση αποδοσης',

    'formación',
    'formacion',
    'capacitación',
    'capacitacion',
    'curso',
    'módulo',
    'modulo',
    'lección',
    'leccion',
    'habilidades',
    'talento',
    'desarrollo profesional',
    'carrera',
    'evaluación del desempeño',
    'evaluacion del desempeno',

    'schulung',
    'training',
    'kurs',
    'modul',
    'lektion',
    'weiterbildung',
    'umschulung',
    'kompetenzaufbau',
    'talent',
    'karriere',
    'leistungsbeurteilung',

    'opplæring',
    'opplaering',
    'kurs',
    'modul',
    'leksjon',
    'kompetanseheving',
    'omskolering',
    'kapasitetsbygging',
    'talent',
    'karriere',
    'prestasjonsevaluering'
  ],

  board_oversight: [
    'board',
    'board of directors',
    'oversight',
    'supervisory',
    'governance structure',
    'committee',
    'esg committee',

    'διοικητικό συμβούλιο',
    'διοικητικο συμβουλιο',
    'δσ',
    'εποπτεία',
    'εποπτεια',
    'επιτροπή',
    'επιτροπη',
    'επιτροπή esg',
    'επιτροπη esg',
    'δομή διακυβέρνησης',
    'δομη διακυβερνησης',

    'consejo',
    'consejo de administración',
    'consejo de administracion',
    'supervisión',
    'supervision',
    'estructura de gobernanza',
    'comité',
    'comite',
    'comité esg',
    'comite esg',

    'vorstand',
    'aufsichtsrat',
    'aufsicht',
    'überwachung',
    'uberwachung',
    'governance-struktur',
    'ausschuss',
    'esg-ausschuss',

    'styre',
    'styret',
    'tilsyn',
    'overvåking',
    'overvaking',
    'styringsstruktur',
    'komité',
    'komite',
    'esg-komité',
    'esg-komite'
  ],

  ethics_anti_corruption: [
    'ethics',
    'ethical',
    'code of conduct',
    'anti-bribery',
    'anti bribery',
    'bribe',
    'corruption',
    'fraud',
    'whistleblow',
    'whistle-blow',
    'sanction',
    'conflict of interest',

    'ηθική',
    'ηθικη',
    'κώδικας δεοντολογίας',
    'κωδικας δεοντολογιας',
    'δωροδοκία',
    'δωροδοκια',
    'διαφθορά',
    'διαφθορα',
    'απάτη',
    'απατη',
    'καταγγελία',
    'καταγγελια',
    'κυρώσεις',
    'κυρωσεις',
    'σύγκρουση συμφερόντων',
    'συγκρουση συμφεροντων',

    'ética',
    'etica',
    'ético',
    'etico',
    'código de conducta',
    'codigo de conducta',
    'soborno',
    'anticorrupción',
    'anticorrupcion',
    'corrupción',
    'corrupcion',
    'fraude',
    'denuncia',
    'sanción',
    'sancion',
    'conflicto de interés',
    'conflicto de interes',

    'ethik',
    'ethisch',
    'verhaltenskodex',
    'bestechung',
    'korruption',
    'betrug',
    'whistleblowing',
    'hinweisgeber',
    'sanktion',
    'interessenkonflikt',

    'etikk',
    'etisk',
    'retningslinjer',
    'bestikkelse',
    'antikorrupsjon',
    'korrupsjon',
    'svindel',
    'varsling',
    'sanksjon',
    'interessekonflikt'
  ],

  risk_compliance: [
    'risk',
    'risk assessment',
    'risk register',
    'mitigation',
    'likelihood',
    'impact',
    'compliance',
    'law',
    'legal',
    'regulation',
    'directive',
    'iso',
    'csrd',
    'esrs',
    'eu-taxonomy',
    'eu taxonomy',

    'κίνδυνος',
    'κινδυνος',
    'αξιολόγηση κινδύνου',
    'αξιολογηση κινδυνου',
    'μητρώο κινδύνων',
    'μητρωο κινδυνων',
    'μετριασμός',
    'μετριασμος',
    'πιθανότητα',
    'πιθανοτητα',
    'αντίκτυπος',
    'αντικτυπος',
    'συμμόρφωση',
    'συμμορφωση',
    'νόμος',
    'νομος',
    'νομικός',
    'νομικος',
    'κανονισμός',
    'κανονισμος',
    'οδηγία',
    'οδηγια',
    'ταξινομία εε',
    'ταξινομια εε',

    'riesgo',
    'evaluación de riesgos',
    'evaluacion de riesgos',
    'registro de riesgos',
    'mitigación',
    'mitigacion',
    'probabilidad',
    'impacto',
    'cumplimiento',
    'ley',
    'legal',
    'regulación',
    'regulacion',
    'directiva',
    'taxonomía de la ue',
    'taxonomia de la ue',

    'risiko',
    'risikobewertung',
    'risikoregister',
    'minderung',
    'wahrscheinlichkeit',
    'auswirkung',
    'compliance',
    'einhaltung',
    'gesetz',
    'rechtlich',
    'verordnung',
    'richtlinie',
    'eu-taxonomie',

    'risiko',
    'risikovurdering',
    'risikoregister',
    'risikoredusering',
    'sannsynlighet',
    'påvirkning',
    'pavirkning',
    'etterlevelse',
    'lov',
    'juridisk',
    'regulering',
    'direktiv',
    'eu-taksonomi'
  ],

  data_privacy_cybersecurity: [
    'data',
    'privacy',
    'gdpr',
    'personal data',
    'cyber',
    'cybersecurity',
    'information security',
    'breach',
    'hack',
    'phishing',

    'δεδομένα',
    'δεδομενα',
    'προσωπικά δεδομένα',
    'προσωπικα δεδομενα',
    'ιδιωτικότητα',
    'ιδιωτικοτητα',
    'gdpr',
    'κυβερνοασφάλεια',
    'κυβερνοασφαλεια',
    'ασφάλεια πληροφοριών',
    'ασφαλεια πληροφοριων',
    'παραβίαση',
    'παραβιαση',
    'χακάρισμα',
    'χακαρισμα',
    'ηλεκτρονικό ψάρεμα',
    'ηλεκτρονικο ψαρεμα',

    'datos',
    'privacidad',
    'rgpd',
    'datos personales',
    'ciberseguridad',
    'seguridad de la información',
    'seguridad de la informacion',
    'brecha',
    'hackeo',
    'phishing',

    'daten',
    'datenschutz',
    'dsgvo',
    'personenbezogene daten',
    'cyber',
    'cybersicherheit',
    'informationssicherheit',
    'datenpanne',
    'hacking',
    'phishing',

    'data',
    'personvern',
    'gdpr',
    'personopplysninger',
    'cyber',
    'cybersikkerhet',
    'informasjonssikkerhet',
    'databrudd',
    'hacking',
    'phishing'
  ],

  executive_remuneration: [
    'executive',
    'management bonus',
    'remuneration',
    'incentive',
    'stock option',
    'variable pay',

    'διοίκηση',
    'διοικηση',
    'εκτελεστικό στέλεχος',
    'εκτελεστικο στελεχος',
    'μπόνους διοίκησης',
    'μπονους διοικησης',
    'αμοιβή',
    'αμοιβη',
    'κίνητρο',
    'κινητρο',
    'μετοχικά δικαιώματα',
    'μετοχικα δικαιωματα',
    'μεταβλητή αμοιβή',
    'μεταβλητη αμοιβη',

    'ejecutivo',
    'bono de gestión',
    'bono de gestion',
    'remuneración',
    'remuneracion',
    'incentivo',
    'opción sobre acciones',
    'opcion sobre acciones',
    'pago variable',

    'führungskraft',
    'fuhrungskraft',
    'managementbonus',
    'vergütung',
    'vergutung',
    'anreiz',
    'aktienoption',
    'variable vergütung',
    'variable vergutung',

    'leder',
    'ledelse',
    'lederbonus',
    'godtgjørelse',
    'godtgjorelse',
    'insentiv',
    'aksjeopsjon',
    'variabel lønn',
    'variabel lonn'
  ],

  transparency_reporting: [
    'report',
    'reporting',
    'disclosure',
    'kpi',
    'metric',
    'assurance',
    'audit',
    'materiality',
    'esg report',
    'non-financial report',
    'sustainability report',

    'αναφορά',
    'αναφορα',
    'αναφορές',
    'αναφορες',
    'δημοσιοποίηση',
    'δημοσιοποιηση',
    'δείκτης',
    'δεικτης',
    'μέτρηση',
    'μετρηση',
    'διασφάλιση',
    'διασφαλιση',
    'έλεγχος',
    'ελεγχος',
    'ουσιαστικότητα',
    'ουσιαστικοτητα',
    'έκθεση esg',
    'εκθεση esg',
    'έκθεση βιωσιμότητας',
    'εκθεση βιωσιμοτητας',

    'informe',
    'informes',
    'reporte',
    'divulgación',
    'divulgacion',
    'indicador',
    'métrica',
    'metrica',
    'aseguramiento',
    'auditoría',
    'auditoria',
    'materialidad',
    'informe esg',
    'informe de sostenibilidad',

    'bericht',
    'berichterstattung',
    'offenlegung',
    'kennzahl',
    'metrik',
    'prüfung',
    'prufung',
    'audit',
    'wesentlichkeit',
    'esg-bericht',
    'nachhaltigkeitsbericht',

    'rapport',
    'rapportering',
    'offentliggjøring',
    'offentliggjoring',
    'indikator',
    'måltall',
    'maltall',
    'sikring',
    'revisjon',
    'vesentlighet',
    'esg-rapport',
    'bærekraftsrapport',
    'baerekraftsrapport'
  ],

  supply_chain_governance: [
    'supplier code of conduct',
    'supplier audit',
    'third party due diligence',
    'screening',
    'vendor assessment',
    'supply chain governance',

    'κώδικας δεοντολογίας προμηθευτών',
    'κωδικας δεοντολογιας προμηθευτων',
    'έλεγχος προμηθευτή',
    'ελεγχος προμηθευτη',
    'δέουσα επιμέλεια τρίτων',
    'δεουσα επιμελεια τριτων',
    'έλεγχος τρίτων',
    'ελεγχος τριτων',
    'αξιολόγηση προμηθευτή',
    'αξιολογηση προμηθευτη',
    'διακυβέρνηση εφοδιαστικής αλυσίδας',
    'διακυβερνηση εφοδιαστικης αλυσιδας',

    'código de conducta de proveedores',
    'codigo de conducta de proveedores',
    'auditoría de proveedores',
    'auditoria de proveedores',
    'debida diligencia de terceros',
    'evaluación de proveedores',
    'evaluacion de proveedores',
    'gobernanza de la cadena de suministro',

    'lieferantenkodex',
    'lieferantenaudit',
    'due diligence dritter',
    'screening',
    'lieferantenbewertung',
    'lieferketten-governance',
    'lieferkettenmanagement',

    'leverandørkodeks',
    'leverandorkodeks',
    'leverandørrevisjon',
    'leverandorrevisjon',
    'tredjeparts due diligence',
    'screening',
    'leverandørvurdering',
    'leverandorvurdering',
    'styring av leverandørkjede',
    'styring av leverandorkjede'
  ]
}

const PHRASES = [
  { rx: /\boil\s+spill(s)?\b/i, sub: 'pollution' },
  { rx: /\bspill\s+response|containment\b/i, sub: 'pollution' },
  { rx: /\brecycling?|recyclable|waste\s+segregation\b/i, sub: 'waste_circularity' },
  { rx: /\bcsrd|esrs|eu[-\s]?taxonomy\b/i, sub: 'risk_compliance' },
  { rx: /\bscope\s*(1|2|3)\b/i, sub: 'climate_emissions' },

  { rx: /διαρρο[ήη]\s+πετρελα[ίι]ου|πετρελαιοκηλ[ίι]δα/i, sub: 'pollution' },
  { rx: /ανακ[ύυ]κλωση|ανακυκλ[ώω]σιμο|διαλογ[ήη]\s+αποβλ[ήη]των/i, sub: 'waste_circularity' },
  { rx: /κλιματικ[ήη]\s+αλλαγ[ήη]|α[έε]ρια\s+θερμοκηπ[ίι]ου/i, sub: 'climate_emissions' },

  { rx: /derrame\s+de\s+petr[oó]leo/i, sub: 'pollution' },
  { rx: /cambio\s+clim[aá]tico|gases\s+de\s+efecto\s+invernadero/i, sub: 'climate_emissions' },
  { rx: /reciclaje|residuos|separaci[oó]n\s+de\s+residuos/i, sub: 'waste_circularity' },

  { rx: /[öo]lverschmutzung|[öo]lunfall/i, sub: 'pollution' },
  { rx: /klimawandel|treibhausgas/i, sub: 'climate_emissions' },
  { rx: /kreislaufwirtschaft|abfalltrennung/i, sub: 'waste_circularity' },

  { rx: /oljeutslipp/i, sub: 'pollution' },
  { rx: /klimaendringer|klimagass/i, sub: 'climate_emissions' },
  { rx: /resirkulering|avfallssortering/i, sub: 'waste_circularity' }
]

function normalizeText(value) {
  return (value || '')
    .toString()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[’‘`´]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/\s+/g, ' ')
    .trim()
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function scoreOne(text, needles) {
  let s = 0
  const normalizedText = normalizeText(text)

  for (const n of needles) {
    const normalizedNeedle = normalizeText(n)
    if (!normalizedNeedle) continue

    const escaped = escapeRegex(normalizedNeedle)
    const r = new RegExp(`(^|[^\\p{L}\\p{N}])${escaped}($|[^\\p{L}\\p{N}])`, 'iu')

    if (r.test(normalizedText)) s += 2
    else if (normalizedText.includes(normalizedNeedle)) s += 1
  }

  return s
}

function computeSubcategoryHits(raw, subject) {
  const text = normalizeText(raw)
  const subj = normalizeText(subject)
  const boost = subj ? 2 : 0
  const hits = {}

  for (const p of PHRASES) {
    if (p.rx.test(raw) || p.rx.test(text)) {
      hits[p.sub] = (hits[p.sub] || 0) + 3
    }
  }

  for (const sub of Object.keys(WORDS)) {
    let s = scoreOne(text, WORDS[sub])
    s += boost * scoreOne(subj, WORDS[sub])
    if (s > 0) hits[sub] = (hits[sub] || 0) + s
  }

  return hits
}

export function categorizeIssueESG(raw, subject) {
  const hits = computeSubcategoryHits(raw, subject)

  let entries = Object.entries(hits).sort((a, b) => b[1] - a[1])

  if (entries.length) {
    const bestScore = entries[0][1]
    entries = entries.filter(([_, score]) => score >= bestScore * 0.5)
  }

  const allSubsSorted = entries.map(([sub]) => sub)
  const chosenSubs = allSubsSorted.slice(0, 5)
  const subcategories = chosenSubs.length ? chosenSubs : []

  const majorScores = {}

  for (const [sub, score] of entries) {
    const major = SUBCATEGORY_TO_MAJOR[sub]
    if (!major) continue
    majorScores[major] = (majorScores[major] || 0) + score
  }

  let majors = Object.entries(majorScores)
    .sort((a, b) => b[1] - a[1])
    .map(([m]) => m)

  if (!majors.length) majors = ['environmental']

  const bestMajorScore = majors.length ? majorScores[majors[0]] : 0

  const selectedMajors = majors.filter(
    m => majorScores[m] && majorScores[m] >= bestMajorScore * 0.5
  )

  const subsByMajor = {}

  for (const sub of chosenSubs) {
    const major = SUBCATEGORY_TO_MAJOR[sub]
    if (!major || !selectedMajors.includes(major)) continue
    if (!subsByMajor[major]) subsByMajor[major] = []
    subsByMajor[major].push(sub)
  }

  if (!subcategories.length) subcategories.push('climate_emissions')

  return { majors: selectedMajors, subsByMajor, subcategories }
}

export function autoTag(raw, subject) {
  return categorizeIssueESG(raw, subject).subcategories.slice(0, 5)
}

export function extractSubject(report) {
  if (!report) return ''

  const patterns = [
    /\*\*Subject:\*\*\s*(.+)/i,
    /Subject:\s*(.+)/i,

    /\*\*Θέμα:\*\*\s*(.+)/i,
    /Θέμα:\s*(.+)/i,

    /\*\*Asunto:\*\*\s*(.+)/i,
    /Asunto:\s*(.+)/i,

    /\*\*Betreff:\*\*\s*(.+)/i,
    /Betreff:\s*(.+)/i,

    /\*\*Emne:\*\*\s*(.+)/i,
    /Emne:\s*(.+)/i
  ]

  for (const rx of patterns) {
    const m = report.match(rx)
    if (m) {
      return m[1]
        .trim()
        .replace(/\*\*/g, '')
        .replace(/\s{2,}/g, ' ')
    }
  }

  return ''
}

export const ESG_STRUCTURE = {
  majors: MAJORS,
  subcategories: SUBCATEGORIES,
  labels: SUBCATEGORY_LABELS
}

export const TAXONOMY_LIST = Object.keys(SUBCATEGORY_LABELS)